spring.application.name=smartdrop-inventory-service

# Active Profile: Defaults to 'dev' (H2 in-memory)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Microservice Port: 8082
server.port=${PORT:8082}

# Application Information for OpenAPI / Swagger Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

documentation.application.title=SmartDrop Inventory & Administration API
documentation.application.description=Microservicio de Gestión de Tanques, Dispositivos IoT, Consumo y Administración del Sistema
documentation.application.version=1.0.0
