services:
  smartdrop-iam-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: smartdrop-iam-service
    container_name: smartdrop-iam-service
    restart: on-failure
    environment:
      PORT: 8081
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
    networks:
      - smartdrop-net

  smartdrop-inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: smartdrop-inventory-service
    container_name: smartdrop-inventory-service
    restart: on-failure
    environment:
      PORT: 8082
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8082"
    networks:
      - smartdrop-net

  smartdrop-analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: smartdrop-analytics-service
    container_name: smartdrop-analytics-service
    restart: on-failure
    environment:
      PORT: 8083
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8083:8083"
    networks:
      - smartdrop-net

  smartdrop-support-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: smartdrop-support-service
    container_name: smartdrop-support-service
    restart: on-failure
    environment:
      PORT: 8084
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8084:8084"
    networks:
      - smartdrop-net

  smartdrop-finance-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: smartdrop-finance-service
    container_name: smartdrop-finance-service
    restart: on-failure
    environment:
      PORT: 8085
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8085:8085"
    networks:
      - smartdrop-net

networks:
  smartdrop-net:
    driver: bridge
