spring.application.name=smartdrop-iam-service

# Active Profile: Defaults to 'dev' (H2 in-memory)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Microservice Port: 8081
server.port=${PORT:8081}

# Application Information for OpenAPI / Swagger Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

documentation.application.title=SmartDrop IAM & Profiles API
documentation.application.description=Microservicio de Autenticación, Gestión de Usuarios, JWT y Perfiles de SmartDrop
documentation.application.version=1.0.0

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentialsSecureKey2026SmartDrop
authorization.jwt.expiration.days=7
