spring.application.name=smartdrop-finance-service

# Active Profile: Defaults to 'dev' (H2 in-memory)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Microservice Port: 8085
server.port=${PORT:8085}

# Application Information for OpenAPI / Swagger Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

documentation.application.title=SmartDrop Finance & Planning API
documentation.application.description=Microservicio de Pagos, Facturación, Monedero Digital, Suscripciones y Planificación de Rutas
documentation.application.version=1.0.0
